<div id="openingtext">
  	<p>ARTISTS</p>
    </div>
	<div id="maincontent">
  	<p>Here are some of the young artists who have performed with the <strong> Greek Chamber Music Project</strong>: <br />
  	  <br />
  	</p>
  	<img src="ellie_falaris_ganelin.jpg" align="right" class="media" /><p><a name="ellieganelin"><strong>Ellie Falaris Ganelin</strong></a> is a flutist with an engaging stage presence and a unique array of influences. While being classically trained, she has explored styles such as jazz, Latin, Brazilian music and rock. She received double degrees in music and journalism from the University of Maryland, where she studied with William Montgomery and Kathleen Trahan. While in college, Ms. Ganelin performed in the university’s symphony and wind orchestras, as well as the Latin jazz ensemble. She has performed and recorded with an indie pop band called the 1959 Hat Company, based in Toledo, Ohio. She has also been active with Opera on Tap, a group that performs classical music in fun, informal settings. Ms. Ganelin is the founder of the Greek Chamber Music Project, uncovering little-known classical works by Greek composers. In collaboration with a number of young, talented artists and co-sponsorship from the Modern Greek Department at the University of Michigan, the debut concert sold out. <a href="http://www.elliefalarisganelin.com//" target="_blank" class="link">www.EllieFalarisGanelin.com</a>
</p>
<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="pantelis_polychronidis">&nbsp;</a></p>
<table align="left" width="220" class="medialeft" >
<tr><td><img src="pantelis_polychronidis.jpg" align="left" /></td></tr>
<tr><td><div id="caption">Photo by M. Chatzistamatiou</div></td></tr>
</table>
<p><strong>Dr. Pantelis Polychronidis</strong>is  a collaborative pianist, educator and scholar who performs regularly in both  the United States and Europe. He has been in-demand as a collaborative pianist  and coach, and has performed in Austria, Germany, Greece, Holland, Slovakia and  the U.S. Combining the best elements of the European and American musical  traditions, he is equally at home in the art song and the operatic repertoire,  as well as in chamber music. His current major project focuses on relations  between music and poetry: he performed an evening-long recital with settings of  C. P. Cavafy poems in four languages by 17 composers, which he performed on six  U.S. campuses in 2012 (Indiana, Michigan, Columbia, Yale, Brown and Iowa) and  is in the planning stage for both a European and another American tour in 2013.</p>
He  is currently on the Collaborative Piano Faculty of the Institute for the  International Education of Students (IES), Vienna, where he coaches  undergraduate voice students and instrumentalists from across the United States.  He regularly plays for Christa Ludwig’s private lessons at the Vienna State  Opera and performs at the Franz-Schubert-Institut in Baden bei Wien, of which  he is an alumnus. In winter 2012 he was a Martin Luther King, Jr.-César  Chávez-Rosa Parks Visiting Professor of Music at the University of Michigan. In  the summer of 2012 he was on the Collaborative Faculty of the American  Institute of Musical Studies (AIMS) in Graz, Austria. Dr. Polychronidis studied  with Martin Katz at the University of Michigan where he was awarded his  Doctorate of Musical Arts (DMA) in Collaborative Piano. During his U.S. studies  he was supported by Fulbright and Onassis scholarships. He has completed two postdoctoral  programs at the University for Music and Performing Arts in Vienna in Lied  accompanying and in chamber music, with Charles Spencer and Roswitha Heintze,  respectively.
<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="mariangela_chatzistamatiou">&nbsp;</a></p>
<p>
<img src="mariangela_chatzistamatiou.jpg" class="media" />
Soprano <strong>Mariangela Chatzistamatiou </strong>was  born and raised in Greece where she received the fundamentals in vocal  training. As a classical performer she made her professional debut at the age  of 21 when she performed the role of the Third Boy in Mozart’s Die Zauberflöte  at the National Theater of Northern Greece. She also served as member of the  chorus at the National Theater of Northern Greece where she appeared in Don  Giovanni, Un ballo in maschera, and Tosca. During her residency in Bowling  Green State University (Bowling Green, Ohio), Ms. Chatzistamatiou was included  in the cast of several Bowling Green Opera Theater productions, such as Pelléas  and Mélisande, L’incoronazione di Poppea, Orpheus in the Underworld, and La  virtùde’ stralid’amore in collaboration with the Eastman School of Music. During  2011-2012 season, she served as a member of the all-professional choir of the  Mariner’s Church of Detroit, Mich., where she specialized in the performance of  early English choral music. </p>
<p>She  received a Master’s in Music in Voice Performance at Bowling Green State  University in 2011. She also holds degrees from the Università per Stranieri di  Perugia (Italy) and the Université Paris Sorbonne (France). Ms. Chatzistamatiou  also holds degrees in photography and has worked as a freelance photographer in  the United States, France and Greece. She also worked as photographer and  videographer for College of Music at Bowling Green State University. She  specializes in artists’ publicity photography and has photographed such artists  as Branford Marsalis, Arturo O’Farrill, David Lang, Marin Alsop, David Bixler,  Rodney Whitaker, New York Voices and more. In 2012 she joined the faculty at  the College of Music of Mahidol University in Thailand where she teaches  applied voice and language-oriented courses.</p>
<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="alekos_syropoulos">&nbsp;</a></p>
<p>
  <img src="alekos_syropoulos.jpg" class="medialeft" />Saxophonist <strong>Alekos Syropoulos</strong>, a  student of professor Andrew Bishop, is a senior pursuing a BFA in Jazz Studies  and a minor in Modern Greek Studies at the University of Michigan. Recently,  Alekos placed as a semi-finalist in the 2012 North American Saxophone Alliance Jazz  Solo Competition, was a co-winner with Michael Malis for the 2012 Platsis award  for his composition &quot;Pathos,&quot; was accepted into the 2012 Conservatory  of Amsterdam International Summer Jazz Workshop, and played with the Michigan  Latin Jazz Ensemble and the Vincent Chandler Septet at the 2012 Detroit  International Jazz Festival. He also leads two ensembles: Syropoulos Rex — a  jazz-inspired experimental-soul band — and his Greek-Jazz fusion project with  Michael Malis. His groups have performed at the University of Michigan Museum  of Art, Kerrytown Concert House, Rackham Auditorium, The Canterbury House, the  Michigan League, the Virgil H. Carr Center in Detroit, the Opa Music Festival,  The Blind Pig, and The Stone (hosted by Geri Allen in New York). This is his  second year as the saxophone mentor in the Detroit Civic Youth Jazz Ensemble  program, working alongside Sean Dobbins, Tad Weed, Rayse Biggs and many others.</p>
<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="michael_malis">&nbsp;</a></p>
<p>
<img src="michael_malis.jpg" class="media" />
<strong>Michael Malis</strong> is a jazz pianist and composer from the Detroit area. He graduated with distinction from the University of Michigan, where he studied jazz piano and English. While at U of M, he had the pleasure of studying with the eminent jazz pianist Geri Allen. In 2008, he was a featured soloist at the Kennedy Center in Washington D.C., as part of their ongoing “Conservatory Project.” As a composer, he recently won “Best Original Score” in the 2011 Lightworks Film Festival for his score for the short film “Slash/Fiction.” He is currently working on scoring another short film, and is also writing music for a theater production. He performs regularly in the Detroit area, both in his own group and as a sideman in various groups. Although he is schooled in the jazz tradition, Malis keeps himself broad by playing in a wide varitey of groups. He currently plays keyboards for SomeOthaShip Connect’s MC Kadence, and has shared the stage with a diverse array of artists, including Douglas Ewart, Vincent York, Michele Ramo and Vincent Chandler. In July 2011, Malis, along with Alekos Syropoulos, performed a special concert bridging traditional Greek music with the American jazz tradition. <a href="http://www.michaelmalis.com//" target="_blank" class="link">www.MichaelMalis.com</a>
</p>
<p>&nbsp;</p>
<hr width="500" size="1" color="#666" />
<a name="karen_donato">&nbsp;</a></p>
<p> <img src="karendonato_web.jpg" class="medialeft" />Violinist <strong>Karen Donato</strong> is an active performer and teacher in  Southeast Michigan. She is a tenured member of the Ann Arbor, Flint and Saginaw  Bay Symphonies, and plays regularly with other local ensembles including the  Lansing and Kalamazoo Symphonies. Ms. Donato is a member of the opera orchestra  at Pine Mountain Music Festival in Houghton, Mich. In addition, she maintains  private studios at her home in Canton and at the Flint School of Performing  Arts, where she is the founder and director of the Adult String Ensemble. Ms.  Donato is also an enthusiastic solo performer and chamber musician. Every  August, she performs at Strings On The Bay, a chamber music series based in  Escanaba, Mich.  Recent chamber  performances have included appearances at Orchestra Hall in Detroit and  Kerrytown Concert House in Ann Arbor, among others. She holds an MM in Violin  Performance from the University of Michigan. <a href="http://karendonato.com/" target="_blank" class="link">www.KarenDonato.com</a></p>
<p>&nbsp;</p>
<hr width="500" size="1" color="#666" />
<a name="maria_bessmeltseva">&nbsp;</a></p>
<p>
  <img src="mariabessmeltseva_web.jpg" class="media" />From an early age, Russian-born violinist <strong>Dr. Maria Bessmeltseva</strong> has performed in  the concert halls of Russia, Poland, Lithuania, Italy, and the United States of  America. Dr. Bessmeltseva's solo career has taken her from the celebrated  stages of the Kennedy Center in Washington, D.C., to the Glinka Philharmonic  Chamber Hall and St. Petersburg State Capella in St. Petersburg, Russia. She  has appeared as a soloist with the Symphony of the Mountains in Tennessee, the  Firelands Symphony in Ohio, and the Hot Springs Music Festival Orchestra in  Arkansas. In addition to her live performances, Dr. Bessmeltseva has also  appeared on local TV and radio stations in Bloomfield Hills, MI, Rutland, VT,  and South Hadley, MA. Dr. Bessmeltseva earned her Bachelor's degree from the  Oberlin Conservatory of Music, where she studied with Gregory Fulkerson and  Alla Aranovskaya. <br />
  Dr. Bessmeltseva is a frequent prizewinner in competitions,  including the International Mazur Youth Chamber Music Competition, Elizabeth  Harper Vaughn Concerto Competition, Eighth Annual Hellam Young Artists'  Competition, Tuesday Scholarship Musical Competition, Firelands Symphony  Concerto Competition, Lima Young Artists Competition, and Joan and Daniel  Rutenberg International Chamber Music Competition. She frequently collaborates  with other chamber musicians, including Theodore Arm, Brinton Smith, Tom  Kraines, Christoph Huebner, and Yehonatan Berick. She achieved her DMA at the  University of Michigan School of Music, Theatre and Dance, under the direction  of Yehonatan Berick. <a href="http://www.mariabessmeltseva.com/" target="_blank" class="link">www.MariaBessmeltseva.com</a></p>
<hr width="500" size="1" color="#666" />
<a name="mark_dover">&nbsp;</a>
<p> <img src="mark_web.jpg" class="medialeft" />Hailed by Opera News for his &quot;exemplary clarinet  playing,&quot;<strong> clarinetist Mark Dover</strong> is quickly becoming a fixture of the New  York music scene. He recently earned his Master of Music from Manhattan School  of Music where he studied with David Krakauer. He received his B.M. from the  University of Michigan School of Music, Theatre, and Dance. Recently, Mark was  added as a finalist for the New World Symphony, and performed with that  orchestra in September and March of the 2011-12 season. He was also invited on  behalf of the Swiss Global Artistic Foundation to perform Brahms' Sonata in E  flat Major at the Swiss Ambassador's Residence in Washington, D.C. with pianist  David Fung. He returned to D.C. in November to perform Stravinsky's L'histoire  du Soldat at the Embassy of the Russian Federation to the U.S.A. with conductor  Geoffrey Simon. Since moving to New York in 2010, Mark has already performed at  all the major concert halls, including Carnegie Hall, Weill Recital Hall, Avery  Fisher Hall, Alice Tully Hall, and Merkin Hall. He has performed with the  Detroit Symphony under Leonard Slatkin, at the Kent/Blossom Festival, and as a  founding member of the new music collective Existential pilot. With an  extensive background in jazz and improvised music, Mark performed as a saxophonist  with The Temptations at the age of 19, on board Cunard's Queen Mary 2 and Queen  Victoria, as clarinet soloist with the Stan Rubin Orchestra, and has played at  numerous jazz venues in New York including Cornelia Street Cafe, Barbez, The  Shrine and Swing 46. His major mentors include David Krakauer, Deborah  Chodacki, Nathan Williams and Jay DeVries.</p>
<p>&nbsp;</p>  
<p align="center">- <a href="index.php?page=artists" target="_top" class="link">Back to top</a> -</p>
      <div></div>
  </div>