<div class="grid_10 prefix_1">
<div id="openingtext">
  	<p>ARTISTS</p>
    </div>
	<div id="maincontent">
  	<p>Here are some of the young artists who have performed with the <strong> Greek Chamber Music Project</strong>: <br /><a name="ellieganelin">&nbsp;</a>
  	  <br />
  	</p>
  	<img src="ellie_falaris_ganelin.jpg" align="right" class="media" />
  	<p><strong>Ellie Falaris Ganelin</strong> is a flutist with an  engaging stage presence and a unique array of influences. Classically trained,  she is also versed in jazz, Latin, Brazilian music, rock, and experimental  music. She received double degrees in music and journalism from the University  of Maryland, where she studied with William Montgomery and Kathleen Trahan. She  has performed and recorded with indie pop band 1959 Hat Company and appears on  their Hearts Intersect EP. She has also been a member of Opera on Tap, bringing  opera and classical music to fun, informal settings. Ms. Ganelin has most  recently explored experimental improvisation, having performed at the  Contemporary Art Institute of Detroit, the Red Room in Baltimore, and as part  of Edgefest in Ann Arbor, MI. Ms. Ganelin is the founder of the Greek Chamber Music  Project (GCMP), performing successful concerts in Ann Arbor and the Washington, D.C. region, with more cities to come. Ms. Ganelin is currently based in San Francisco, where  she lives with her husband, Ilya. <a href="http://www.ellieganelin.com//" target="_blank" class="link">www.EllieGanelin.com</a>
    </p>

<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="mary-voutsas">&nbsp;</a></p>
<p><img src="mary-voutsas.jpg" class="media" /><strong>Mary-Victoria Voutsas</strong> is a "powerful," and "enthralling pianist" (CUA Tower paper). She has studied under Tatyana Hearne, Julie Hahn, Ann Kang, and Yuliya Gorenman. Ms. Voutsas has also performed master classes and recitals for several acclaimed pianists, including Yuri Didenko, Dr. Joseph Banowetz, and Christopher O'Reilly. Ms. Voutsas has toured extensively as a pianist, and as a classical musician she has performed at many notable venues including the Czech, Polish, French, and Thai embassies, Catholic University's Ward Hall, Lisner Auditorium, and the Kennedy Center's Millennium Stage and Terrace Theatre. Ms. Voutsas performed for the Thai King Bhumibol Adulyadej's birthday celebration, and at one of the inaugural concerts of Pope John Paul II's Cultural Center in Washington, DC She was praised in an article later that her "performance enthralled the listeners making the evening a wonderful tribute." Ms. Voutsas has participated in numerous competitions and in 2011, 2014, and 2015, was invited to the Bartok-Kabalevsky-Prokofiev Piano Competition in Italy. Ms. Voutsas was awarded the Watkins Prize in 2011, and Director's Musician of Achievement award in 2013 at American University. She has debuted new music for Jonathan Kolm and Dimitar Naumoff, and performed for the Rob Kapilow "What Makes It Great?" program in 2013 accompanied by the Peabody Chamber Orchestra. Ms. Voutsas also has experience in harpsichord performance, choral conducting, and is currently studying prepared piano with Laurie Hudicek. Ms. Voutsas resides in the Washington DC area where she teaches piano and theory. She looks forward to releasing the first installment of Dvorak's Poetic Tone Pictures, Op. 85, in September 2015.</p>
<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="anna-hennessy">&nbsp;</a></p>

<p><img src="anna-hennessy.jpg" class="media" align="right" /><br />
<strong>Anna Matijasic Hennessy</strong>, MM, is an eclectic violinist. She has performed and recorded extensively with numerous classical, Americana, jazz and rock ensembles in the United States, Europe and South America. Anna studied violin and music education at the University of Virginia and James Madison University. She regularly performs with regional chamber music ensembles and teaches orchestra in Fairfax County.</p>
<p>&nbsp;

<hr width="500" size="1" color="#666" />
<a name="pantelis_polychronidis">&nbsp;</a></p>
<table align="left" width="220" class="medialeft" >
<tr><td><img src="pantelis_polychronidis.jpg" align="left" /></td></tr>
<tr><td><div id="caption">Photo by M. Chatzistamatiou</div></td></tr>
</table>
<p><strong>Dr. Pantelis Polychronidis</strong> is a collaborative pianist, educator and scholar who performs regularly in both the U.S. and Europe. He is Senior Lecturer at the University for Music and Performing Arts in Vienna (Department of Voice/Opera) and also teaches at Vienna Konservatorium and at Wiener Musikakademie. He served as an Assistant Professor in Residence at the University of Nevada, Las Vegas and in  2012 he was a Martin Luther King, Jr.-César Chávez-Rosa Parks Visiting Professor of Music at the University of Michigan. Dr. Polychronidis was on the Collaborative Piano Faculty of the American Institute of Musical Studies (AIMS) in Graz, Austria and often performs at the Franz-Schubert-Institut in Baden bei Wien, of which he is an alumnus.</p>
<p>Combining the best elements of the European and American musical traditions, he is equally at home in the art song and the operatic repertoire as well as in chamber music. He has been in demand as a collaborative pianist and coach, and has performed in Austria, Germany, Greece, Holland, Slovakia, Belgium, England and the U.S. He received his Bachelor in Musical Studies from the University of Athens with emphasis on ethnomusicology and historical musicology. He obtained his M.A. in Solo Piano and Collaborative Piano from Bowling Green State University, Ohio. Next, he studied with Martin Katz at the University of Michigan where he was awarded his Doctorate of Musical Arts (DMA) in Collaborative Piano. While at Michigan he accompanied the studio classes of George Shirley and the late Shirley Verrett. During his U.S. studies Dr. Polychronidis was supported by a Fulbright and an Onassis scholarship. He has completed two Postdoctoral Programs at the University for Music and Performing Arts in Vienna, in Lied accompanying and Chamber music, with Charles Spencer and Roswitha Heintze respectively.</p>
<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="mariangela_chatzistamatiou">&nbsp;</a></p>
<p>
<img src="mariangela_chatzistamatiou.jpg" class="media" />
Soprano <strong>Mariangela Chatzistamatiou </strong>was  born and raised in Greece where she received the fundamentals in vocal  training. As a classical performer she made her professional debut at the age  of 21 when she performed the role of the Third Boy in Mozart’s Die Zauberflöte  at the National Theater of Northern Greece. She also served as member of the  chorus at the National Theater of Northern Greece where she appeared in Don  Giovanni, Un ballo in maschera, and Tosca. During her residency in Bowling  Green State University (Bowling Green, Ohio), Ms. Chatzistamatiou was included  in the cast of several Bowling Green Opera Theater productions, such as Pelléas  and Mélisande, L’incoronazione di Poppea, Orpheus in the Underworld, and La  virtùde’ stralid’amore in collaboration with the Eastman School of Music. During  2011-2012 season, she served as a member of the all-professional choir of the  Mariner’s Church of Detroit, Mich., where she specialized in the performance of  early English choral music. </p>
<p>She  received a Master’s in Music in Voice Performance at Bowling Green State  University in 2011. She also holds degrees from the Università per Stranieri di  Perugia (Italy) and the Université Paris Sorbonne (France). Ms. Chatzistamatiou  also holds degrees in photography and has worked as a freelance photographer in  the United States, France and Greece. She also worked as photographer and  videographer for College of Music at Bowling Green State University. She  specializes in artists’ publicity photography and has photographed such artists  as Branford Marsalis, Arturo O’Farrill, David Lang, Marin Alsop, David Bixler,  Rodney Whitaker, New York Voices and more. In 2012 she joined the faculty at  the College of Music of Mahidol University in Thailand where she teaches  applied voice and language-oriented courses.</p>
<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="alekos_syropoulos">&nbsp;</a></p>
<p>
  <img src="alekos_syropoulos.jpg" class="medialeft" /> A native of  Miami, Florida, <strong>Alekos Syropoulos</strong> has become known for his funky yet worldy approach to creating music as a saxophonist. Rooted as a jazz musician, Alekos continuously seeks creative minds and listeners so he can share his musical message. He performs avidly in Los Angeles and dedicates much of his time to composing, songwriting, producing, and teaching.  By the ripe age of 23, Alekos has had the distinct privilege to perform and/or record with James Moody, Terell Stafford, Christian McBride, Dave Liebman, Ellen Rowe &amp; Ingrid Jensen, Tad Weed, Sean Dobbins, Vincent Chandler, The Macpodz, Robert Hurst, Raquel Rodriguez, The Vibrometers, Bay Cities, Sammy Miller &amp; The Congregation, Ruslan Sirota, Barbara Morrison, WILDCAT WILDCAT, and Vulfpeck. He was a finalist in the 2012 NASA Competition, won 1st place in the 2013 Yamaha Young Artist Competition as a jazz saxophonist, and 2nd place in the 2015 International Vandoren Emerging Artists Competition. He is an active music teacher as well and taught on faculty at the Detroit Symphony Orchestra&rsquo;s Youth Civic Jazz Program from 2011 to 2013. He currently teaches saxophone, woodwinds, and piano at the South Pasadena Music Conservatory but also teaches his own private studio of students. <a href="http://www.alekosmusic.com/" target="_blank" class="link">www.AlekosMusic.com</a></p>
<p>&nbsp;
<hr width="500" size="1" color="#666" />
<a name="michael_malis">&nbsp;</a></p>
<p>
<img src="michael_malis.jpg" class="media" />
<strong>Michael Malis</strong>Michael Malis is a pianist and composer based in Detroit, MI. As a pianist, he has shared the stage with a diverse array of musicians, including notables such as Marcus Belgrave, Jaribu Shahid, Ken Filiano, Andrew Bishop, Dennis Coffey, and Marion Hayden. He also leads a trio which showcases his own original music. He has performed at the Kennedy Center, the Detroit Jazz Festival, The Stone (NYC), and the Detroit Institute of Arts, among other venues. In September of 2013, Malis began his appointment as the Musical Director at the Canterbury House in Ann Arbor. The Canterbury House is a performance space and Episcopal Church that has been a staple in the Ann Arbor performing arts community for years. In his tenure as Musical Director, he has programmed adventurous Jazz Masses, curated a Concert Series featuring cutting-edge musicians such as William Hooker, Tatsuya Nakatani, James Cornish, and others, and put on a the yearly Canterbury House Music Festival, featuring local and regional musicians. As a composer, he was awarded &quot;Best Musical Score&quot; in the 2011 Lightworks Film Festival for his score to the short film &quot;Slash/Fiction.&quot; He has continued to write music for film since then, scoring a total of three short films and one full-length feature film. Malis most recently composed the score to the full length feature film “Papou,” from Mother and Midwife productions. The film is set to be released later in 2015. He began writing music for theater in 2012, writing the musical score for “The Mute Quire”, a play by the Fratellanza Theater Company, which premiered at the New Theater Project in Ypsilanti, MI, in June of 2012 to critical acclaim. “The Mute Quire” was recently remounted in Galway, Ireland in 2014 at the Galway Fringe Festival. His second collaboration with Fratellanza, “String Up the Moon,” premiered in Detroit to critical acclaim in September of 2013. He started playing the piano at age five, and started writing music shortly thereafter. In high school, he began his studies in earnest with Detroit jazz piano legend Bess Bonnier. After high school, he attended the University of Michigan, where he studied with the eminent jazz pianist Geri Allen.
 <a href="http://www.michaelmalis.com/" target="_blank" class="link">www.MichaelMalis.com</a>
</p>
<p>&nbsp;</p>
<hr width="500" size="1" color="#666" />
<a name="karen_donato">&nbsp;</a></p>
<p> <img src="karendonato_web.jpg" class="medialeft" />Violinist <strong>Karen Donato</strong> is an active performer and teacher in  Southeast Michigan. She is a tenured member of the Ann Arbor, Flint and Saginaw  Bay Symphonies, and plays regularly with other local ensembles including the  Lansing and Kalamazoo Symphonies. Ms. Donato is a member of the opera orchestra  at Pine Mountain Music Festival in Houghton, Mich. In addition, she maintains  private studios at her home in Canton and at the Flint School of Performing  Arts, where she is the founder and director of the Adult String Ensemble. Ms.  Donato is also an enthusiastic solo performer and chamber musician. Every  August, she performs at Strings On The Bay, a chamber music series based in  Escanaba, Mich.  Recent chamber  performances have included appearances at Orchestra Hall in Detroit and  Kerrytown Concert House in Ann Arbor, among others. She holds an MM in Violin  Performance from the University of Michigan. <a href="http://karendonato.com/" target="_blank" class="link">www.KarenDonato.com</a></p>
<p>&nbsp;</p>
<hr width="500" size="1" color="#666" />
<a name="maria_bessmeltseva">&nbsp;</a></p>
<p>
  <img src="mariabessmeltseva_web.jpg" class="media" />From an early age, Russian-born violinist <strong>Dr. Maria Bessmeltseva</strong> has performed in  the concert halls of Russia, Poland, Lithuania, Italy, and the United States of  America. Dr. Bessmeltseva's solo career has taken her from the celebrated  stages of the Kennedy Center in Washington, D.C., to the Glinka Philharmonic  Chamber Hall and St. Petersburg State Capella in St. Petersburg, Russia. She  has appeared as a soloist with the Symphony of the Mountains in Tennessee, the  Firelands Symphony in Ohio, and the Hot Springs Music Festival Orchestra in  Arkansas. In addition to her live performances, Dr. Bessmeltseva has also  appeared on local TV and radio stations in Bloomfield Hills, MI, Rutland, VT,  and South Hadley, MA. Dr. Bessmeltseva earned her Bachelor's degree from the  Oberlin Conservatory of Music, where she studied with Gregory Fulkerson and  Alla Aranovskaya. <br />
  Dr. Bessmeltseva is a frequent prizewinner in competitions,  including the International Mazur Youth Chamber Music Competition, Elizabeth  Harper Vaughn Concerto Competition, Eighth Annual Hellam Young Artists'  Competition, Tuesday Scholarship Musical Competition, Firelands Symphony  Concerto Competition, Lima Young Artists Competition, and Joan and Daniel  Rutenberg International Chamber Music Competition. She frequently collaborates  with other chamber musicians, including Theodore Arm, Brinton Smith, Tom  Kraines, Christoph Huebner, and Yehonatan Berick. She achieved her DMA at the  University of Michigan School of Music, Theatre and Dance, under the direction  of Yehonatan Berick. <a href="http://www.mariabessmeltseva.com/" target="_blank" class="link">www.MariaBessmeltseva.com</a></p>
<hr width="500" size="1" color="#666" />
<a name="mark_dover">&nbsp;</a>
<p> <img src="mark_web.jpg" class="medialeft" />Hailed by Opera News for his &quot;exemplary clarinet  playing,&quot;<strong> clarinetist Mark Dover</strong> is quickly becoming a fixture of the New  York music scene. He recently earned his Master of Music from Manhattan School  of Music where he studied with David Krakauer. He received his B.M. from the  University of Michigan School of Music, Theatre, and Dance. Recently, Mark was  added as a finalist for the New World Symphony, and performed with that  orchestra in September and March of the 2011-12 season. He was also invited on  behalf of the Swiss Global Artistic Foundation to perform Brahms' Sonata in E  flat Major at the Swiss Ambassador's Residence in Washington, D.C. with pianist  David Fung. He returned to D.C. in November to perform Stravinsky's L'histoire  du Soldat at the Embassy of the Russian Federation to the U.S.A. with conductor  Geoffrey Simon. Since moving to New York in 2010, Mark has already performed at  all the major concert halls, including Carnegie Hall, Weill Recital Hall, Avery  Fisher Hall, Alice Tully Hall, and Merkin Hall. He has performed with the  Detroit Symphony under Leonard Slatkin, at the Kent/Blossom Festival, and as a  founding member of the new music collective Existential pilot. With an  extensive background in jazz and improvised music, Mark performed as a saxophonist  with The Temptations at the age of 19, on board Cunard's Queen Mary 2 and Queen  Victoria, as clarinet soloist with the Stan Rubin Orchestra, and has played at  numerous jazz venues in New York including Cornelia Street Cafe, Barbez, The  Shrine and Swing 46. His major mentors include David Krakauer, Deborah  Chodacki, Nathan Williams and Jay DeVries.</p>
<p>&nbsp;</p>  
<p align="center">- <a href="index.php?page=artists" target="_top" class="link">Back to top</a> -</p>
      <div></div>
  </div>
  </div>